name: Trigger Web Deploy

on:
  push:
    branches:
      - develop

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Encode Config Secret
        id: encode-secret
        run: |
          echo "${{ secrets.CONFIG_JSON }}" | base64 > encoded_config.txt
          echo "CONFIG_ENCODED=$(cat encoded_config.txt)" >> $GITHUB_ENV

      - name: Trigger Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          repository: team-b1nd/dodam-web-deploy-config
          event-type: trigger-deploy
          client-payload: |
            {
              "repo_name": "${{ github.repository }}",
              "branch": "${{ github.ref }}",
              "source_directory": "./build",
              "destination_directory": "/dodam/myinfo",
              "config_secret": "${{ env.CONFIG_ENCODED }}"
            }
