name: Trigger Web Deploy

on:
  push:
    branches:
      - develop

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Config JSON File
        id: create-json 
        uses: jsdaniell/create-json@v1.2.2 
        with:
          name: "config.json"  # 생성할 파일 이름
          json: ${{ secrets.CONFIG_JSON }}  # JSON 데이터
          dir: './src/config'  # 파일이 생성될 디렉토리 

      - name: Trigger Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          repository: team-b1nd/dodam-web-deploy-config
          event-type: trigger-deploy
          client-payload: |
            {
              "repo_name": "${{ github.repository }}",
              "branch": "${{ github.ref }}",
              "source_directory": "./build",
              "destination_directory": "/dodam/myinfo",
              "config_secret": "$(cat ./src/config/config.json)"
            }
